import { useSeo } from '@/hooks/useSeo';
import LegalPageLayout from '@/components/LegalPageLayout';

export default function Terms() {
  useSeo({
    title: 'Terms of Use',
    description: 'Read the terms of use for MoneyCalc. Understand the terms and conditions for using our financial calculators.',
    path: '/terms',
  });

  return (
    <LegalPageLayout title="Terms of Use" lastUpdated="September 2026">
      <div className="space-y-6">
        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">1. Acceptance of Terms</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            By accessing and using MoneyCalc, you accept and agree to be bound by these Terms of Use.
            If you do not agree with any part of these terms, please do not use our website.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">2. Use of Our Services</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            MoneyCalc provides free financial calculators for informational and educational purposes
            only. You may use our calculators for personal, non-commercial purposes. You agree not
            to misuse the website, attempt to disrupt its operation, or use it for any unlawful activity.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">3. No Financial Advice</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            The results generated by our calculators are estimates based on the inputs you provide.
            They do not constitute financial, investment, tax, or legal advice. Always consult a
            qualified professional before making financial decisions.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">4. Accuracy of Information</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            We strive to ensure our calculators use accurate formulas and up-to-date tax slabs.
            However, we do not guarantee that all results are error-free. Tax laws, interest rates,
            and financial regulations change frequently. You are responsible for verifying
            results with official sources.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">5. Intellectual Property</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            The content, design, and code of MoneyCalc are our intellectual property. You may not
            copy, reproduce, or distribute our content without permission.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">6. Third-Party Links</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            Our website may contain links to third-party websites. We are not responsible for the
            content or practices of these external sites.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">7. Limitation of Liability</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            MoneyCalc is provided &quot;as is&quot; without warranties of any kind. We are not liable for
            any damages arising from the use of our calculators or reliance on their results.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">8. Changes to Terms</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            We may update these Terms of Use at any time. Continued use of the website after changes
            constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-bold text-gray-900">9. Contact</h2>
          <p className="mt-2 text-sm text-gray-600 leading-relaxed">
            For questions about these terms, contact us at support@moneycalc.in.
          </p>
        </section>
      </div>
    </LegalPageLayout>
  );
}
